secret:
  db:
    username: postgres
    password: pirsumgres
  token:
    key: sdhfhsdfggusdfkuygsdufggfbgvtsdgfurfbocvajnrgaiuetjrbg
  aws:
    accessKey: AKIA36ODUCGAKR6Z33S5
    secretKey: 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
